import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {randomUUID} from "node:crypto";
import {PGlite} from "@electric-sql/pglite";
import {describeDNASignals,dnaMutationSchema,parseDNASnapshot} from "../src/lib/reading-dna.js";
const a="11111111-1111-4111-8111-111111111111",b="22222222-2222-4222-8222-222222222222",id="33333333-3333-4333-8333-333333333333";
test("DNA evidence respects consent, ownership, reset cutoff and uncertainty",()=>{
  const settings={personalisation_enabled:true,use_recent_ratings:true,use_dnf_reasons:false};
  const base={id,category:"pacing",label:"Fast pacing",active:true,internal_weight:.9,updated_at:"2026-10-07T10:00:00Z",created_at:"2026-10-01T10:00:00Z"};
  const books=[{id:a,title:"Own book",rating:5},{id:b,title:"Removed",rating:4,isRemoved:true}];
  const rows=[{...base,source_type:"rating",evidence:[a,a,b,"foreign"]},{...base,id:a,source_type:"dnf",evidence:[a]},{...base,id:b,source_type:"onboarding",evidence:[]},{...base,id:randomUUID(),source_type:"mixed",evidence:[a]}];
  const signals=describeDNASignals(rows,books,settings);
  assert.equal(signals[0].evidence.length,1);assert.equal(signals[0].strength,"emerging");assert.match(signals[0].description,/rating alone/);
  assert.equal(signals[1].active,false);assert.equal(signals[1].evidence.length,0);assert.equal(signals[2].evidence[0].bookId,null);assert.equal(signals[3].active,false);
  assert.equal(describeDNASignals(rows,books,{...settings,personalisation_enabled:false}).some(signal=>signal.active),false);
  assert.equal(describeDNASignals(rows,books,settings,"2026-10-06T00:00:00Z").length,1);
  const future={...rows[0],created_at:"2026-10-07T00:00:00Z",evidence:[{id:a,occurred_at:"2026-10-07T00:00:00Z"}]};
  assert.equal(describeDNASignals([future],books,settings,"2026-10-06T00:00:00Z")[0].evidence.length,1);
  assert.equal(describeDNASignals([{...future,evidence:[a]}],books,settings,"2026-10-06T00:00:00Z")[0].active,false);
  const offset={...future,created_at:"2026-10-06T01:00:00+02:00",evidence:[{id:a,occurred_at:"2026-10-06T01:00:00+02:00"}]};
  assert.equal(describeDNASignals([offset],books,settings,"2026-10-06T00:00:00Z").length,0);
  assert.equal(describeDNASignals([{...future,evidence:offset.evidence}],books,settings,"2026-10-06T00:00:00Z")[0].active,false);
  const approved=[a,b,id].map(bookId=>({id:bookId,title:"Approved",rating:4}));
  assert.equal(describeDNASignals([{...rows[0],internal_weight:.1,evidence:[a,b,id]}],approved,settings)[0].strength,"strong");
  const valid={action:"reduce",operationId:randomUUID(),signalId:id,expectedUpdatedAt:base.updated_at};
  assert.equal(dnaMutationSchema.safeParse(valid).success,true);assert.equal(dnaMutationSchema.safeParse({...valid,userId:b}).success,false);
  assert.equal(dnaMutationSchema.safeParse({action:"reset",operationId:randomUUID(),confirmation:"DELETE"}).success,false);
  assert.equal(parseDNASnapshot(JSON.stringify({userId:a,fetchedAt:1,enabled:true,completed:true,resetAt:null,signals}),b),null);
});
test("DNA RPCs enforce RLS, idempotency, Undo conflicts and preference-preserving reset",async()=>{
 const db=new PGlite();try{
  await db.exec(`create schema auth;create schema extensions;create role anon;create role authenticated;grant usage on schema auth to anon,authenticated;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select (current_setting('request.jwt.claims',true)::jsonb->>'sub')::uuid$$;`);
  for(const name of ["202609220001_initial_schema_rls.sql","202610060001_reading_setup.sql","202610060002_library_detail.sql","202610060003_recommendations.sql","202610060004_settings_import.sql","202610070002_reading_dna.sql"])await db.exec((await readFile(new URL("../supabase/migrations/"+name,import.meta.url),"utf8")).replace("create extension if not exists pgcrypto with schema extensions;",""));
  await db.exec(`insert into auth.users(id) values('${a}'),('${b}');insert into public.books(id,google_books_id,title)values('${id}','example','Example');insert into public.user_books(user_id,book_id,notes,rating)values('${a}','${id}','Private',5);insert into public.reading_dna_signals(id,user_id,category,label,source_type)values('${id}','${a}','genre','Fantasy','onboarding');update public.profiles set reading_setup_preferences='{"genres":["Fantasy"],"storyElements":[],"pacing":"","moods":[]}',reading_setup_completed_at=now() where id='${a}';update public.ai_settings set personalisation_enabled=true,use_recent_ratings=true where user_id='${a}';`);
  const role=async(user,which="authenticated")=>db.exec(`reset role;select set_config('request.jwt.claims','${JSON.stringify(user?{sub:user}:{})}',false);set role ${which};`);
  const read=async()=>(await db.query("select *,updated_at::text as stamp from public.reading_dna_signals where id=$1",[id])).rows[0];
  const change=(op,action,stamp,undo=null)=>db.query("select public.change_reading_dna($1,$2,$3,$4,$5)",[op,id,action,stamp,undo]);
  await role(a);const original=await read(),op=randomUUID();await change(op,"reduce",original.stamp);await change(op,"reduce",original.stamp);
  assert.equal(Number((await read()).internal_weight),.25);assert.equal((await read()).influence_state,"reduced");
  await assert.rejects(change(randomUUID(),"remove",original.stamp),error=>error.code==="40001");
  await change(randomUUID(),"undo",null,op);assert.equal(Number((await read()).internal_weight),.5);
  const removeOp=randomUUID();await change(removeOp,"remove",(await read()).stamp);assert.equal((await read()).active,false);
  await change(randomUUID(),"keep",(await read()).stamp);await assert.rejects(change(randomUUID(),"undo",null,removeOp),error=>error.code==="40001");
  await role(b);assert.equal((await db.query("select * from public.reading_dna_changes")).rows.length,0);await assert.rejects(change(randomUUID(),"remove",original.stamp),error=>error.code==="42501");assert.equal((await db.query("update public.reading_dna_changes set undone=true returning id")).rows.length,0);
  await assert.rejects(db.query("insert into public.reading_dna_changes(id,user_id,signal_id,action)values($1,$2,$3,'keep')",[randomUUID(),b,id]),error=>error.code==="42501");
  await role(null,"anon");await assert.rejects(db.query("select * from public.reading_dna_changes"),error=>error.code==="42501");await assert.rejects(change(randomUUID(),"keep",original.stamp),error=>error.code==="42501");
  await role(a);await db.query("insert into public.reading_dna_signals(user_id,category,label,source_type)values($1,'pacing','Learned','rating')",[a]);
  const reset=randomUUID();await db.query("select public.reset_reading_dna($1)",[reset]);
  assert.equal((await db.query("select * from public.reading_dna_signals")).rows.length,1);assert.equal((await read()).active,true);
  assert.equal((await db.query("select personalisation_enabled,use_recent_ratings from public.ai_settings")).rows[0].personalisation_enabled,true);
  assert.deepEqual((await db.query("select reading_setup_preferences from public.profiles")).rows[0].reading_setup_preferences.genres,["Fantasy"]);
  assert.equal((await db.query("select notes,rating from public.user_books")).rows[0].notes,"Private");
  await db.query("select public.save_reader_settings($1)",[{kind:"reset",confirmation:"RESET"}]);
  await db.query("insert into public.reading_dna_signals(user_id,category,label,source_type)values($1,'pacing','Future activity','rating')",[a]);
  await db.query("select public.reset_reading_dna($1)",[reset]);assert.equal((await db.query("select * from public.reading_dna_signals")).rows.length,2);
  await assert.rejects(change(randomUUID(),"undo",null,op),error=>error.code==="40001");
 }finally{await db.close();}
});
