import test from 'node:test';import assert from 'node:assert/strict';import {recommendationContext} from '../src/lib/recommendation-data.js';
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
test('Gemini activity examples respect independent permissions, Stop controls and the Reset cutoff',async()=>{
 const tables={profiles:[{id:a,display_name:'Reader',reading_dna_reset_at:null}],ai_settings:[{user_id:a,personalisation_enabled:true,use_recent_ratings:true,use_recent_history:false,use_dnf_reasons:false}],user_books:[{id:b,user_id:a,book_id:b,status:'finished',rating:1,notes:'SECRET PRIVATE NOTES',is_removed:false,updated_at:'2026-10-07T12:00:00Z',rating_recorded_at:'2026-10-07T12:00:00Z',reading_completed_at:'2026-10-07T10:00:00Z',books:{google_books_id:'owned',title:'Public book',authors:['Writer'],description:'Public description',categories:['Fantasy']}}],reading_dna_signals:[{id:b,user_id:a,active:false,influence_state:'stopped',category:'rating_genre',label:'Lower ratings · Fantasy',source_type:'rating'}]};
 const supabase={from(table){let single=false;const where=[];const q={select(){return q},eq(k,v){where.push([k,v]);return q},order(){return q},limit(){return q},range(){return q},single(){single=true;return q},then(resolve){const rows=tables[table].filter(r=>where.every(([k,v])=>r[k]===v));return Promise.resolve({data:single?rows[0]:rows,error:null}).then(resolve)}};return q}};
 let ctx=await recommendationContext(supabase,a);assert.equal(ctx.activity[0].rating,1);assert.equal('status' in ctx.activity[0],false);assert.equal(JSON.stringify(ctx.activity).includes('SECRET'),false);assert.equal(ctx.signals.length,0);assert.equal(ctx.controls[0].influence,'stopped');
 tables.ai_settings[0].use_recent_ratings=false;tables.ai_settings[0].use_recent_history=true;ctx=await recommendationContext(supabase,a);assert.equal(ctx.activity[0].status,'finished');assert.equal('rating' in ctx.activity[0],false);assert.deepEqual(ctx.controls,[]);
 tables.profiles[0].reading_dna_reset_at='2026-10-07T11:00:00Z';ctx=await recommendationContext(supabase,a);assert.deepEqual(ctx.activity,[]);
 tables.ai_settings[0].use_recent_ratings=true;ctx=await recommendationContext(supabase,a);assert.equal(ctx.activity[0].rating,1);assert.equal('status' in ctx.activity[0],false);
 tables.ai_settings[0].personalisation_enabled=false;ctx=await recommendationContext(supabase,a);assert.deepEqual(ctx.activity,[]);assert.deepEqual(ctx.controls,[]);
});
