"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {defaultReaderPreferences,settingsMutationSchema} from "@/lib/reader-settings";
import {clearReaderCache} from "@/lib/clear-reader-cache";
import {publishReaderPreferences} from "./ReaderPreferencesRuntime";
import SettingsShell from "./SettingsShell";
import CsvLibraryImport from "./CsvLibraryImport";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import TextField from "@/components/ui/TextField";
import Toggle from "@/components/ui/Toggle";
import InlineAlert from "@/components/ui/InlineAlert";
import styles from "./Settings.module.css";
function Row({title,description,onClick,href,danger=false}){const content=<><span className={styles.icon} aria-hidden="true">{danger?"!":"✦"}</span><span className={styles.copy}><strong>{title}</strong><small>{description}</small></span><span className={styles.arrow} aria-hidden="true">›</span></>;return href?<Link href={href} className={styles.row}>{content}</Link>:<button type="button" className={styles.row} onClick={onClick}>{content}</button>;}
const views={root:["Settings","Your controls, clearly grouped"],ai:["Personalisation & AI","Control how recommendations use your data"],signals:["Personalisation & AI","Choose what can shape suggestions"],appearance:["Appearance","Theme and reading comfort"],accessibility:["Accessibility","Motion, contrast and text"],notifications:["Notifications","Optional and off by default"],privacy:["Privacy","Understand and manage your data"],account:["Account","Profile, session and deletion"],profile:["Edit profile","Update your account details"],logout:["Log out","Confirm sign out"],reset:["Reset Reading DNA","Your Library stays untouched"],delete:["Delete account","What deletion removes"],verify:["Delete account","Verify before deletion"],final:["Delete account","Final confirmation"],import:["Import Library","Bring your reading history to Vela"],password:["Password","Secure email recovery"]};
export default function SettingsScreen({initial,initialView="root",userId,email,createdAt}){
  const router=useRouter();const [settings,setSettings]=useState(initial||{userId,email,createdAt,name:"Reader",pendingEmail:null,preferences:defaultReaderPreferences,permissions:{enabled:false,ratings:false,history:false,dnf:false}});
  const [view,setView]=useState(initialView),[error,setError]=useState(initial?"":"Settings could not load. Retry before changing your preferences."),[notice,setNotice]=useState("");
  const [pending,setPending]=useState(false),[unavailable,setUnavailable]=useState(!initial),[name,setName]=useState(initial?.name||"Reader"),[newEmail,setNewEmail]=useState(email),[password,setPassword]=useState(""),[confirmation,setConfirmation]=useState("");
  const [failedChange,setFailedChange]=useState(null);
  function go(value){if(pending)return;setView(value);setError(failedChange?"Your choices are retained but not confirmed. Retry saving them.":"");setNotice("");setPassword("");setConfirmation("");}
  async function request(url,body,method="POST"){const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Your changes could not be confirmed. Please retry.");return result;}
  async function save(change){if(pending||unavailable)return false;const parsed=settingsMutationSchema.safeParse(change);if(!parsed.success){setError("Check your choices and try again.");return false;}setPending(true);setError("");setNotice("");
    if(change.kind==="preferences")setSettings(value=>({...value,preferences:change.preferences}));
    if(change.kind==="permissions"){const {kind,...permissions}=change;setSettings(value=>({...value,permissions}));}
    try{const result=await request("/api/settings",parsed.data,"PATCH");setSettings(result);setFailedChange(null);publishReaderPreferences(userId,result.preferences);if(result.preferences.haptics&&typeof navigator.vibrate==="function")navigator.vibrate(15);setNotice(change.kind==="reset"?"Inferred Reading DNA and corrections reset. Your setup choices, permissions and Library are preserved.":"Changes saved. Discover uses your current permissions.");router.refresh();return true;}
    catch(error){setFailedChange(parsed.data);setError(error.message);return false;}finally{setPending(false);}}
  async function retry(){setPending(true);try{const result=await request("/api/settings",null,"GET");setSettings(result);setName(result.name);setNewEmail(result.email);setUnavailable(false);setError("");publishReaderPreferences(userId,result.preferences);}catch(error){setError(error.message);}finally{setPending(false);}}
  function permission(key,value){const permissions={...settings.permissions,[key]:value};if(key==="enabled"&&!value)Object.assign(permissions,{ratings:false,history:false,dnf:false});save({kind:"permissions",...permissions});}
  async function preference(key,value){if(["reminders","digest","nudges"].includes(key)&&value){if(typeof Notification==="undefined"){setError("This browser does not support notifications. You can still use all reading features.");return;}try{const permission=await Notification.requestPermission();if(permission!=="granted"){setError("Notifications are blocked. Allow them in your browser settings to enable this reminder.");return;}}catch{setError("Notification permission could not be requested.");return;}}
    save({kind:"preferences",preferences:{...settings.preferences,[key]:value}});}
  async function profile(event){event.preventDefault();if(pending)return;setError("");setNotice("");
    const input=settingsMutationSchema.safeParse({kind:"profile",name});if(!input.success){setError("Enter a name between 1 and 60 characters.");return;}
    const emailChanged=newEmail.trim()!==settings.email;if(emailChanged&&!password){setError("Enter your current password to change your email.");return;}
    setPending(true);let nameSaved=false;
    try{const result=await request("/api/settings",input.data,"PATCH");nameSaved=true;setSettings(result);
      if(emailChanged){const updated=await request("/api/account",{kind:"email",email:newEmail.trim(),password});setSettings({...result,...updated});setNotice(updated.pendingEmail?"Name saved. Confirm your email change using the links sent by Supabase.":"Profile saved.");}
      else setNotice("Profile saved.");setPassword("");router.refresh();
    }catch(error){setError(`${nameSaved?"Your name was saved. ":""}${error.message}`);}finally{setPending(false);}}
  function ending(destination){window.dispatchEvent(new CustomEvent("vela:session-ending",{detail:{destination}}));}
  async function logout(){setPending(true);setError("");ending("/signed-out");try{const result=await createClient().auth.signOut({scope:"local"});if(result.error)throw result.error;clearReaderCache(userId);window.location.replace("/signed-out");}catch{ending("/login");setError("Could not log out. Please try again.");setPending(false);}}
  async function verify(event){event.preventDefault();setPending(true);setError("");try{await request("/api/account",{kind:"verify-delete",password});setPassword("");setView("final");}catch(error){setError(error.message);}finally{setPending(false);}}
  async function remove(){setPending(true);setError("");ending("/account-deleted");try{const result=await request("/api/account",{confirmation},"DELETE");if(!result.deleted)throw new Error("Deletion could not be confirmed.");clearReaderCache(userId);window.location.replace("/account-deleted");}catch(error){ending("/login");setError(error.message);setPending(false);}}
  async function download(){setPending(true);setError("");try{const response=await fetch("/api/settings/export",{cache:"no-store"});if(!response.ok)throw new Error("Your download could not be prepared. Please retry.");const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download="vela-account.json";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice("Your account archive was downloaded.");}catch(error){setError(error.message);}finally{setPending(false);}}
  async function recovery(){setPending(true);setError("");try{const result=await createClient().auth.resetPasswordForEmail(settings.email,{redirectTo:`${location.origin}/auth/callback?next=/reset-password`});if(result.error)throw result.error;setNotice("Password recovery requested. Check your email for the secure reset link.");}catch{setError("Could not send the reset email. Please try again.");}finally{setPending(false);}}
  const p=settings.preferences,a=settings.permissions;const [title,subtitle]=views[view];const toggle=(key,label,description,group="preferences")=><Toggle key={key} className={styles.toggle} label={label} description={description} checked={(group==="preferences"?p:a)[key]} loading={pending} disabled={unavailable||(group==="permissions"&&key!=="enabled"&&!a.enabled)} onChange={event=>group==="preferences"?preference(key,event.target.checked):permission(key,event.target.checked)}/>;
  const profileCard=<Card className={styles.profile}><span className={styles.avatar} aria-hidden="true">{settings.name.trim().slice(0,1).toUpperCase()}</span><div><h2>{settings.name}</h2><p>{settings.email}</p>{view==="account"&&<p>Member since {new Date(settings.createdAt||createdAt).toLocaleDateString("en-ZA",{month:"long",year:"numeric"})}</p>}</div></Card>;
  return <SettingsShell title={title} subtitle={pending&&view==="final"?"Deletion in progress":subtitle} onBack={view==="root"?null:()=>go(["profile","password","logout","delete"].includes(view)?"account":view==="verify"?"delete":view==="final"?"verify":view==="signals"||view==="reset"?"ai":"root")} showNavigation={!['profile','logout','delete','verify','final'].includes(view)}>
    {error&&<InlineAlert type="error">{error}</InlineAlert>}{failedChange&&<Button loading={pending} onClick={()=>save(failedChange)}>Retry saving choices</Button>}{unavailable&&<Button loading={pending} onClick={retry}>Retry loading settings</Button>}{notice&&<p className={styles.notice} role="status">{notice}</p>}
    {view==="root"&&<>{profileCard}<Row title="Personalisation & AI" description="Control suggestions and signals" onClick={()=>go("ai")}/><Row title="Accessibility" description="Motion, text and contrast" onClick={()=>go("accessibility")}/><Row title="Privacy" description="Understand and manage data" onClick={()=>go("privacy")}/><Row title="Account" description="Profile, log out and delete" onClick={()=>go("account")}/><Row title="Import Library" description="Add books from a CSV export" onClick={()=>go("import")}/><Row title="Appearance" description="Theme and reading comfort" onClick={()=>go("appearance")}/><Row title="Notifications" description="Optional reading reminders" onClick={()=>go("notifications")}/></>}
    {view==="ai"&&<><Card className={`${styles.panel} ${styles.purple}`}><h2>AI follows your lead.</h2><p>Suggestions can be personalised without hiding the signals or limiting your control.</p></Card>{toggle("enabled","Personalised recommendations","Use permitted signals in Discover","permissions")}<Row title="Data signal controls" description="Ratings, history and DNF reasons" onClick={()=>go("signals")}/><Row title="Review Reading DNA" description="Inspect your permitted signals" href="/dna"/><Row title="Edit reading choices" description="Genres, story elements, pacing and mood" href="/setup"/><Row title="Reset Reading DNA" description="Library stays untouched" danger onClick={()=>go("reset")}/></>}
    {view==="signals"&&<><h2 className={styles.intro}>Choose what Vela can learn from.</h2>{toggle("ratings","Use my ratings","Stars and review feedback","permissions")}{toggle("history","Use my reading history","Finished books and progress","permissions")}{toggle("dnf","Use my DNF reasons","Only reasons you approved","permissions")}{toggle("enabled","Personalised recommendations","Turn personalised suggestions on or off","permissions")}</>}
    {view==="accessibility"&&<><Card className={styles.panel}><h2>Access begins<br/>at the foundation.</h2><p>All controls remain labelled, reachable and readable.</p></Card>{toggle("reduceMotion","Reduce motion","Replace movement with gentle fades")}{toggle("highContrast","Higher contrast","Strengthen borders and labels")}{toggle("haptics","Haptic feedback","Confirm saves on supported devices")}<Row title="Text scaling" description="Follows device settings; larger text available" onClick={()=>go("appearance")}/></>}
    {view==="appearance"&&<><h2 className={styles.intro}>Theme</h2><div className={styles.choices}>{["system","light","dark"].map(theme=><Button key={theme} variant={p.theme===theme?"primary":"secondary"} aria-pressed={p.theme===theme} disabled={pending||unavailable} onClick={()=>preference("theme",theme)}>{theme[0].toUpperCase()+theme.slice(1)}</Button>)}</div><div className={styles.choices}><Button variant={p.textScale==="system"?"primary":"secondary"} onClick={()=>preference("textScale","system")} disabled={pending||unavailable}>System text</Button><Button variant={p.textScale==="large"?"primary":"secondary"} onClick={()=>preference("textScale","large")} disabled={pending||unavailable}>Larger text</Button></div><div className={styles.choices}>{["comfortable","compact"].map(density=><Button key={density} variant={p.density===density?"primary":"secondary"} aria-pressed={p.density===density} disabled={pending||unavailable} onClick={()=>preference("density",density)}>{density[0].toUpperCase()+density.slice(1)}</Button>)}</div><Card className={styles.panel}><h2>A calm page for every chapter.</h2><p>This preview reflects theme and spacing choices.</p></Card></>}
    {view==="notifications"&&<><Card className={styles.panel}><h2>Quiet by default.</h2><p>Vela asks for notification permission only after you choose a reminder.</p><p className={styles.small}>Browser reminders run while Vela is open. Closed-app push and email delivery are not configured.</p></Card><TextField className={styles.field} label="Reminder time" type="time" value={p.reminderTime} disabled={pending||unavailable} onChange={event=>preference("reminderTime",event.target.value)}/>{toggle("reminders","Reading reminders","Daily at your chosen time")}{toggle("digest","Recommendation reminder","Mondays · your saved recommendations")}{toggle("nudges","Progress nudges","A quiet daily prompt, never guilt-based")}</>}
    {view==="privacy"&&<><Card className={styles.panel}><h2>Your data has a job.</h2><p>Vela stores account details, your Library and only the personalisation signals you permit.</p></Card><Row title="Personalisation controls" description="Choose which signals AI may use" onClick={()=>go("signals")}/><Row title="Stored reading data" description="Library, progress, ratings and notes" href="/library"/><Row title="Download my data" description="Portable account archive" onClick={download}/><Row title="Import Library" description="Read a CSV export into your shelves" onClick={()=>go("import")}/><Row title="Delete account" description="Permanently remove account data" danger onClick={()=>go("delete")}/></>}
    {view==="account"&&<>{profileCard}{settings.pendingEmail&&<InlineAlert type="info">Email change awaiting confirmation: {settings.pendingEmail}</InlineAlert>}<Row title="Edit profile" description="Name and email" onClick={()=>go("profile")}/><Row title="Password" description="Request a secure password reset" onClick={()=>go("password")}/><Row title="Log out" description="End this session" onClick={()=>go("logout")}/><Row title="Delete account" description="Permanent and irreversible" danger onClick={()=>go("delete")}/></>}
    {view==="profile"&&<form className={styles.form} onSubmit={profile}><TextField className={styles.field} label="Name" value={name} maxLength={60} required disabled={pending||unavailable} onChange={event=>setName(event.target.value)}/><TextField className={styles.field} label="Email" type="email" value={newEmail} required disabled={pending||unavailable} onChange={event=>setNewEmail(event.target.value)}/><TextField className={styles.field} label="Current password" type="password" autoComplete="current-password" value={password} disabled={pending||unavailable} helperText="Required only when changing your email." onChange={event=>setPassword(event.target.value)}/><Button className={styles.primary} type="submit" loading={pending} disabled={unavailable}>Save changes</Button></form>}
    {view==="password"&&<><Card className={styles.panel}><h2>Reset securely.</h2><p>Send a password reset link to {settings.email}. Follow it to choose your new password.</p></Card><Button className={styles.primary} loading={pending} onClick={recovery}>Send reset email</Button></>}
    {view==="logout"&&<div className={styles.confirmation}><Card className={styles.panel}><h2>Log out of Vela?</h2><p>Your Library and Reading DNA stay safely linked to your account.</p><Button className={styles.primary} onClick={logout} loading={pending}>Log out</Button><Button className={styles.secondary} variant="secondary" disabled={pending} onClick={()=>go("account")}>Stay signed in</Button></Card></div>}
    {view==="reset"&&<><Card className={`${styles.panel} ${styles.danger}`}><h2>Start Reading DNA again?</h2><p>This clears inferred signals and signal corrections. Your setup choices, privacy permissions, Library, ratings, notes and progress stay intact. Reset cannot be undone.</p></Card><Button variant="destructive" href="/dna?view=reset">Review Reading DNA reset</Button><Button variant="secondary" onClick={()=>go("ai")} disabled={pending}>Cancel</Button></>}
    {view==="delete"&&<><Card className={`${styles.panel} ${styles.danger}`}><h2>Before you delete</h2><p>This permanently removes:</p><ul><li>Account and profile details</li><li>Library, progress and notes</li><li>Ratings, recommendations and Reading DNA</li><li>Personalisation permissions and private manual books</li></ul><strong>This cannot be recovered after deletion.</strong></Card><Button variant="destructive" className={styles.primary} disabled={unavailable} onClick={()=>go("verify")}>Continue to verification</Button><Button variant="secondary" className={styles.secondary} onClick={()=>go("account")}>Cancel</Button></>}
    {view==="verify"&&<form className={styles.form} onSubmit={verify}><h2 className={styles.intro}>Confirm it’s you.</h2><p>Re-enter your password before the final deletion step.</p><TextField className={styles.field} label="Email" value={settings.email} readOnly/><TextField className={styles.field} label="Password" type="password" required autoComplete="current-password" value={password} disabled={pending} onChange={event=>setPassword(event.target.value)}/><Button className={styles.primary} type="submit" loading={pending}>Verify identity</Button><Button href="/forgot-password" variant="tertiary">Forgot password?</Button></form>}
    {view==="final"&&<div className={styles.confirmation}><Card className={`${styles.panel} ${styles.danger}`}><p>FINAL STEP</p><h2>{pending?"Deleting account…":"Delete your account?"}</h2><p>This is the last confirmation. The account and its data cannot be restored.</p><TextField className={styles.field} label="Type DELETE" value={confirmation} disabled={pending} onChange={event=>setConfirmation(event.target.value)}/><Button variant="destructive" className={styles.primary} disabled={confirmation!=="DELETE"} loading={pending} onClick={remove}>Delete account</Button><Button className={styles.secondary} variant="secondary" disabled={pending} onClick={()=>go("account")}>Cancel</Button></Card></div>}
    {view==="import"&&<CsvLibraryImport/>}
  </SettingsShell>;
}


